CONFIG_FILE = "config.json"
MODULE_DIR = "src/modules"
DEFAULT_TIMER_INTERVAL = 5 * 60
STATIC_FOLDER = "src/static"
TEMPLATE_FOLDER = "src/templates"
SERVER_HOST = "127.0.0.1"
SERVER_PORT = "7070"
UNCATEGORIZED_NAME = "Sonstiges"
